controllers/LotController.php
<?php

namespace app\controllers;

use app\models\LotStructure;
use app\models\LotTask;
use app\models\LotToUser;
use app\models\search\LotTaskSearch;
use app\models\User;
use Yii;
use app\models\Lot;
use app\models\search\LotSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * LotController implements the CRUD actions for Lot model.
 */
class LotController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lot models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LotSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['id' => SORT_DESC]);

        /** @var User $identity */
        $identity = Yii::$app->user->identity;
        if (!$identity->isSuperAdmin()) {
            $dataProvider->query->andWhere(['company_id' => $identity->company_id]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Lot model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $task_model = new LotTask();
        $task_model->lot_id = $model->id;
        $task_model->done = 0;

        $lotTaskSearchModel = new LotTaskSearch();
        $lotTaskProvider = $lotTaskSearchModel->search(['lot_id' => $model->id]);
        $lotTaskProvider->query->orderBy(['done' => SORT_ASC]);
        $lotTaskProvider->query->andWhere(['lot_id' => $model->id]);

        $structure_model = new LotStructure();
        $structure_model->lot_id = $model->id;
        $structure_model->structure = LotStructure::find()->forLot($model->id)->all();
        $structure_model->setTotals();

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Лот #" . $id,
                'content' => $this->renderAjax('view', [
                    'model' => $model,
                    'taskModel' => $task_model,
                    'lotTaskSearchModel' => $lotTaskSearchModel,
                    'lotTaskProvider' => $lotTaskProvider,
                    'structure_model' => $structure_model,
                ]),
                'footer' => Html::button('Закрыть',
                        ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Редактировать', ['update', 'id' => $id],
                        ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $model,
                'lot_task_model' => $task_model,
                'lotTaskSearchModel' => $lotTaskSearchModel,
                'lotTaskDataProvider' => $lotTaskProvider,
                'structure_model' => $structure_model,
            ]);
        }
    }

    /**
     * Creates a new Lot model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Lot();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Создание лота",
                    'size' => 'large',
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                ];
            } else {
                if ($model->load($request->post()) && $model->save()) {
                    return [
                        'forceReload' => '#lot-index-pjax',
                        'forceClose' => true,
                    ];
                } else {
                    return [
                        'title' => "Создание лота",
                        'size' => 'large',
                        'content' => $this->renderAjax('create', [
                            'model' => $model,
                        ]),
                        'footer' => Html::button('Закрыть',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                            Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                    ];
                }
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Lot model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        $model->access_users = (new LotToUser())->getUsersForLot($model->id);

        Yii::info($model->access_users, 'test');

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Редактирование лота #" . $id,
                    'size' => 'large',
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else {
                if ($model->load($request->post()) && $model->save()) {
                    return [
                        'forceReload' => '#lot-index-pjax',
                        'forceClose' => true,
                    ];
                } else {
                    return [
                        'title' => "Редактирование лота #" . $id,
                        'size' => 'large',
                        'content' => $this->renderAjax('update', [
                            'model' => $model,
                        ]),
                        'footer' => Html::button('Закрыть',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                            Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                    ];
                }
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing Lot model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

    /**
     * Delete multiple existing Lot model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if ($request->isAjax) {

views/lot/_columns.php
<?php

use app\models\Lot;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'name',
        'content' => function (Lot $model) {
            return \yii\helpers\Html::a($model->name, ['/lot/view', 'id' => $model->id]);
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'lot_status_id',
        'filter' => (new \app\models\LotStatus())->getList(),
        'content' => function (Lot $model) {
            return $model->lotStatus ? $model->lotStatus->name : null;
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'filter' => (new \app\models\LotGroup())->getList(),
        'attribute' => 'lot_group_id',
        'content' => function (Lot $model) {
            return $model->lotGroup ? $model->lotGroup->name : null;
        }
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'id',
    // ],

//    [
//        'class' => '\kartik\grid\DataColumn',
//        'attribute' => 'description',
//        'content' => function (Lot $model){
//            return substr($model->description, 0, 200);
//        }
//    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'pos_num',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'end_date',
    ],
//    [
//        'class' => '\kartik\grid\DataColumn',
//        'attribute' => 'auction_link',
//    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'auction_price',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'rate',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'max_auction_rate',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'min_auction_rate',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'sale_profit',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'time_to_realization',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'client_found',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'lot_location',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'opponent_auction_form_num',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'form_is_filing',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'deposit_is_payed',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'tbankrot_link',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'debtor_info',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'stages',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'is_archive',
    // ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'access_users',
        'content' => function (Lot $model) {
            return $model->getAccessUsersList(false);
        }
    ],

    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'competitive_manager_phone',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'competitive_manager_email',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'company_id',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
        'viewOptions' => ['title' => 'View', 'data-toggle' => 'tooltip'],
        'updateOptions' => ['role' => 'modal-remote', 'title' => 'Update', 'data-toggle' => 'tooltip'],
        'deleteOptions' => [
            'role' => 'modal-remote',
            'title' => 'Delete',
            'data-confirm' => false,
            'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Are you sure?',
            'data-confirm-message' => 'Are you sure want to delete this item'
        ],
    ],

];   

views/lot/_form.php
<?php

use app\models\Company;
use app\models\LotGroup;
use app\models\LotStatus;
use app\models\User;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Lot */
/* @var $form yii\widgets\ActiveForm */

/** @var User $identity */
$identity = Yii::$app->user->identity;
?>

<div class="lot-form">

    <?php $form = ActiveForm::begin(); ?>
    <?php if ($identity->isSuperAdmin()): ?>
        <?php
        try {
            echo $form->field($model, 'company_id')->widget(\kartik\select2\Select2::class, [
                'data' => (new Company())->getList(),
                'options' => [
                    'prompt' => 'Выберите компанию'
                ]
            ]);
        } catch (Exception $e) {
            Yii::error($e->getMessage(), '_error');
            echo $e->getMessage();
        } ?>
    <?php else: ?>
        <?= $form->field($model, 'company_id')->hiddenInput()->label(false) ?>
    <?php endif; ?>

    <div class="row">
<!--Левая колонка-->
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-6">

                    <?= $form->field($model, 'lot_status_id')->dropDownList((new LotStatus())->getList(),
                        [
                            'prompt' => 'Выберите статус'
                        ]) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'lot_group_id')->dropDownList((new LotGroup())->getList(),
                        [
                            'prompt' => 'Выберите группу'
                        ]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'description')->textarea(['rows' => 10]) ?>
                </div>
                <div class="col-md-12">
                    <?= $form->field($model, 'debtor_info')->textarea(['rows' => 10]) ?>
                </div>
                <div class="col-md-12">
                    <?= $form->field($model, 'stages')->textarea(['rows' => 10]) ?>
                </div>
            </div>
        </div>
<!--Правая колонка-->
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'pos_num')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'end_date')->input('date') ?>
                </div>
                <div class="col-md-12">
                    <?= $form->field($model, 'auction_link')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'auction_price')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'rate')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'max_auction_rate')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'min_auction_rate')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'sale_profit')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'time_to_realization')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'client_found')->checkbox() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'form_is_filing')->checkbox() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'deposit_is_payed')->checkbox() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'is_archive')->checkbox() ?>
                </div>
                <div class="col-md-12">
                    <?= $form->field($model, 'lot_location')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-12">
                    <?= $form->field($model, 'opponent_auction_form_num')->textInput() ?>
                </div>

                <div class="col-md-12">
                    <?= $form->field($model, 'tbankrot_link')->textInput() ?>
                </div>
                <div class="col-md-12">
                    <?php
                    try {
                        echo $form->field($model, 'access_users')->widget(\kartik\select2\Select2::class, [
                            'data' => ArrayHelper::map(User::getUsers()->all(), 'id', 'fio'),
                            'options' => [
                                'placeholder' => '...',
                                'multiple' => true,
                            ],
                            'pluginOptions' => [
                            ]
                        ]);
                    } catch (Exception $e) {
                        Yii::error($e->getMessage(), '_error');
                        echo $e->getMessage();
                    } ?>

                </div>


                <div class="col-md-12">
                    <?= $form->field($model, 'competitive_manager_phone')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-12">
                    <?= $form->field($model, 'competitive_manager_email')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
        </div>
    </div>











    <?php if (!Yii::$app->request->isAjax) { ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update',
                ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/lot/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Lot */

?>
<div class="lot-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/lot/index.php
<?php

use app\widgets\LotView;
use yii\bootstrap\Modal;
use johnitvn\ajaxcrud\CrudAsset;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\LotSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lots';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<?php Pjax::begin([
    'id' => 'lot-index-pjax',
    'enablePushState' => false
]) ?>
<?php
try {
    echo LotView::widget([
        'dataProvider' => $dataProvider,
    ]);
} catch (Exception $e) {
    Yii::error($e->getMessage(), '_error');
    echo $e->getMessage();
} ?>

<?php Pjax::end() ?>
<div class="lot-index">
    <!--    <div id="ajaxCrudDatatable">-->
    <!--        --><?php //echo GridView::widget([
    //            'id'=>'crud-datatable',
    //            'dataProvider' => $dataProvider,
    //            'filterModel' => $searchModel,
    //            'pjax'=>true,
    //            'columns' => require(__DIR__.'/_columns.php'),
    //            'toolbar'=> [
    //                ['content'=>
    //                    Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
    //                    ['role'=>'modal-remote','title'=> 'Create new Lots','class'=>'btn btn-default']).
    //                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
    //                    ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
    //                    '{toggleData}'.
    //                    '{export}'
    //                ],
    //            ],
    //            'striped' => true,
    //            'condensed' => true,
    //            'responsive' => true,
    //            'panel' => [
    //                'type' => 'primary',
    //                'heading' => '<i class="glyphicon glyphicon-list"></i> Lots listing',
    //                'before'=>'<em>* Resize table columns just like a spreadsheet by dragging the column edges.</em>',
    //                'after'=>BulkButtonWidget::widget([
    //                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
    //                                ["bulk-delete"] ,
    //                                [
    //                                    "class"=>"btn btn-danger btn-xs",
    //                                    'role'=>'modal-remote-bulk',
    //                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
    //                                    'data-request-method'=>'post',
    //                                    'data-confirm-title'=>'Are you sure?',
    //                                    'data-confirm-message'=>'Are you sure want to delete this item'
    //                                ]),
    //                        ]).
    //                        '<div class="clearfix"></div>',
    //            ]
    //        ])?>
    <!--    </div>-->
</div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/lot/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Lot */
?>
<div class="lot-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>